import '../support/wooCommerce/categories.commands'
import '../support/wooCommerce/shippingZone.commands'
import '../support/wooCommerce/productReview.commands'
import '../support/wooCommerce/util.commands'
import '../support/wooCommerce/coupons.commands'
